services:
  web:
    container_name: evse_reader
    build: .
    ports:
      - "3030:8000"
    environment:
      - FLASK_ENV=production
    env_file: .env
    volumes:
      - ./container-data:/app/instance
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    
    # Optional:
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true